### ISSUE TITLE
Unexpected argument: max_attempts 

### ISSUE THREAD

**Issue by yassineaboukir** [andresriancho/enumerate-iam#1]
Hi,

It looks like the recent commit (https://github.com/andresriancho/enumerate-iam/commit/0edfae549a65b1fd9f00c82299af86c968ebb3e8) to mitigate the rate limit issue is screwing up the tool execution:

```
2019-06-23 23:49:34,547 - 35055 - [INFO] Attempting common-service describe / list brute force.
Traceback (most recent call last):
  File "./enumerate-iam.py", line 24, in <module>
    main()
  File "./enumerate-iam.py", line 20, in main
    args.region)
  File "/Users/yassineaboukir/Desktop/Hacktools/enumerate-iam/enumerate_iam/main.py", line 204, in enumerate_iam
    output['bruteforce'] = enumerate_using_bruteforce(access_key, secret_key, session_token, region)
  File "/Users/yassineaboukir/Desktop/Hacktools/enumerate-iam/enumerate_iam/main.py", line 74, in enumerate_using_bruteforce
    results = pool.map(check_one_permission, args_generator)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
TypeError: Got unexpected keyword argument 'max_attempts'
```

The issue is due to the fact that `max_attempts` is unexpected as mentioned above. You should have adjusted `retries={'max_attempts': 1}` instead.

Regards.

**Comment by andresriancho** [comment]
Ouch!

PR merged.
