### ISSUE TITLE
enumerate-iam not running 

### ISSUE THREAD

**Issue by sushantdhopat** [andresriancho/enumerate-iam#13]
i run this command after installing the tool and installing all requirements

./enumerate-iam.py --access-key AK*************** --secret-key Mi**************************************

this command give me the error

Traceback (most recent call last):
  File "./enumerate-iam.py", line 4, in <module>
    from enumerate_iam.main import enumerate_iam
  File "/root/enumerate-iam/enumerate_iam/main.py", line 22, in <module>
    import boto3
ImportError: No module named boto3

intstall it boto3 with agian sudo pip install boto3 they give this response 

Requirement already satisfied: boto3 in /usr/local/lib/python3.8/dist-packages (1.16.9)
Requirement already satisfied: s3transfer<0.4.0,>=0.3.0 in /usr/local/lib/python3.8/dist-packages (from boto3) (0.3.3)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /usr/local/lib/python3.8/dist-packages (from boto3) (0.10.0)
Requirement already satisfied: botocore<1.20.0,>=1.19.9 in /usr/local/lib/python3.8/dist-packages (from boto3) (1.19.9)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/lib/python3/dist-packages (from botocore<1.20.0,>=1.19.9->boto3) (2.7.3)
Requirement already satisfied: urllib3<1.26,>=1.25.4; python_version != "3.4" in /usr/local/lib/python3.8/dist-packages (from botocore<1.20.0,>=1.19.9->boto3) (1.25.8)

after i run again the

./enumerate-iam.py --access-key AK*************** --secret-key Mi**************************************

but this again give me same error

Traceback (most recent call last):
  File "./enumerate-iam.py", line 4, in <module>
    from enumerate_iam.main import enumerate_iam
  File "/root/enumerate-iam/enumerate_iam/main.py", line 22, in <module>
    import boto3
ImportError: No module named boto3

how can i solve this error ??? please any help kindly 

Thanks in advance

**Comment by mikerod-sd** [comment]
Create a virtualenv for it and rerun pip.

**Comment by pdelteil** [comment]
Try using python3 directly 

``python3 enumerate-iam.py ``

**Comment by asylla117** [comment]
Try the following:
- create a virtual env and try running python3 directly
$ python3 -m venv <virtual_env_name>
$ pip3 install -r requirements.txt
$ python3 enumerate-iam.py --access-key ACCESS_KEY --secret-key SECRET_KEY [--session-token SESSION_TOKEN]

**Comment by br33z3** [comment]
pip3 install boto3
