### ISSUE TITLE
TypeError: 'dict_keys' object is not subscriptable

### ISSUE THREAD

**Issue by cteodor** [andresriancho/enumerate-iam#4]
Is it Python2 compatible only?
Just tried it with Python3 and got:

```
Traceback (most recent call last):
  File "enumerate-iam.py", line 24, in <module>
    main()
  File "enumerate-iam.py", line 20, in main
    args.region)
  File "enumerate-iam/enumerate_iam/main.py", line 204, in enumerate_iam
    output['bruteforce'] = enumerate_using_bruteforce(access_key, secret_key, session_token, region)
  File "enumerate-iam/enumerate_iam/main.py", line 74, in enumerate_using_bruteforce
    results = pool.map(check_one_permission, args_generator)
  File "/anaconda3/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/anaconda3/lib/python3.7/multiprocessing/pool.py", line 383, in _map_async
    iterable = list(iterable)
  File "/Users/t/Work/aws_/enumerate-iam/enumerate_iam/main.py", line 91, in generate_args
    random.shuffle(service_names)
  File "/anaconda3/lib/python3.7/random.py", line 278, in shuffle
    x[i], x[j] = x[j], x[i]
TypeError: 'dict_keys' object is not subscriptable
```

**Comment by andresriancho** [comment]
yeah, haven't really tested it in py3k

Pull requests for making it compatible for both 2 and 3 are more than welcome

**Comment by andresriancho** [comment]
This should be fixed now
