### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by Wayc0des-Land** [andresriancho/enumerate-iam#7]
Hi,

Today i try your tool for check some AWS Access Key & Secret Key. But I got error like this :

```
 ./enumerate-iam.py --access-key AKIABLABLABLA --secret-key blablablabla--region us-west-2
Traceback (most recent call last):
  File "./enumerate-iam.py", line 24, in <module>
    main()
  File "./enumerate-iam.py", line 20, in main
    args.region)
  File "/home/wayc0de/tools/enumerate-iam/enumerate-iam/enumerate_iam/main.py", line 217, in enumerate_iam
    configure_logging()
  File "/home/wayc0de/tools/enumerate-iam/enumerate-iam/enumerate_iam/main.py", line 207, in configure_logging
    urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
AttributeError: 'module' object has no attribute 'disable_warnings
```

I tried you python2 and python3, but still failed

Thank you

**Comment by andresriancho** [comment]
Might be solved by running: `pip install --upgrade  requests`

**Comment by Wayc0des-Land** [comment]
```
Installing collected packages: urllib3, certifi, chardet, idna, requests
Successfully installed certifi-2019.9.11 chardet-3.0.4 idna-2.8 requests-2.22.0 urllib3-1.25.7
```

still error sir after upgrade module requests

```
./enumerate-iam.py --access-key AKIABLABLABLA --secret-key isAF3IDBLABLABLABLA --region us-west-2
Traceback (most recent call last):
  File "./enumerate-iam.py", line 24, in <module>
    main()
  File "./enumerate-iam.py", line 20, in main
    args.region)
  File "/home/wayc0de/tools/enumerate-iam/enumerate-iam/enumerate_iam/main.py", line 217, in enumerate_iam
    configure_logging()
  File "/home/wayc0de/tools/enumerate-iam/enumerate-iam/enumerate_iam/main.py", line 207, in configure_logging
    urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
AttributeError: 'module' object has no attribute 'disable_warnings'
```

**Comment by yassineaboukir** [comment]
try: `sudo pip3 install urllib3 --upgrade`.
